# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
body = """
{%- macro remote_url() -%}
https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version }}]({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for entry in commits | commit_groups(groups=commit_parsers_groups) %}
    ### {{ entry.group | striptags | trim | upper_first }}
    {% for commit in entry.commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }} \
            {% if commit.remote and commit.remote.pr_number %}\
                ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}))\
            {% else %}\
                ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
            {% endif %}
    {% endfor %}
{% endfor %}

{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
    ## ❤️ New Contributors
{% endif %}\

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
    - @{{ contributor.username }} made their first contribution\
    {% if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{%- endif %}
"""

trim = true
render_always = true

[git]
# Parse Conventional Commits.
conventional_commits = true

# Exclude commits that don't match Conventional Commits.
filter_unconventional = true

# Don't fail if a non-conventional commit exists.
require_conventional = false

# Don't split multiline commits into separate entries.
split_commits = false

# No commit preprocessing needed because GitHub metadata is used
# for PR links.
commit_preprocessors = []

# Allow parsers to skip breaking commits too.
protect_breaking_commits = false

commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^docs", group = "<!-- 3 -->📚 Documentation" },
    { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
    { message = "^style", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test", group = "<!-- 6 -->🧪 Testing" },

    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", group = "<!-- 7 -->📦 Dependencies" },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },

    { message = "^chore|^ci", group = "<!-- 8 -->⚙️ Miscellaneous Tasks" },
    { body = ".*security", group = "<!-- 9 -->🛡️ Security" },
    { message = "^revert", group = "<!-- 10 -->◀️ Revert" },
    { message = ".*", group = "<!-- 11 -->💼 Other" },
]

filter_commits = false
fail_on_unmatched_commit = false

link_parsers = []

use_branch_tags = false
topo_order = false
topo_order_commits = true

# Oldest -> newest within each release section.
sort_commits = "oldest"

recurse_submodules = false